//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositorioAcademico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprobanteRegistro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComprobanteRegistro()
        {
            this.RegistroDeMateria = new HashSet<RegistroDeMateria>();
        }
    
        public long Id { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<int> IdInscripcionCarrera { get; set; }
        public int IdUsuario { get; set; }
        public short IdEstado { get; set; }
        public Nullable<short> IdMotivoRegistroEspecial { get; set; }
    
        public virtual InscripcionCarrera InscripcionCarrera { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistroDeMateria> RegistroDeMateria { get; set; }
    }
}
