//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositorioAcademico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Docente
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<short> IdNivelEstudio { get; set; }
        public Nullable<short> IdDenominacion { get; set; }
        public Nullable<short> IdProfesion { get; set; }
        public Nullable<int> NIT { get; set; }
        public string NUA { get; set; }
        public Nullable<short> IdEstado { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public string Pin { get; set; }
        public Nullable<int> NroFolio { get; set; }
        public Nullable<byte> AntiguedadDocencia { get; set; }
        public Nullable<byte> AntiguedadLaboral { get; set; }
        public int IdTipoDocente { get; set; }
        public Nullable<int> IdClasificacionDocente { get; set; }
        public Nullable<long> IdMoodleUsuario { get; set; }
        public string EmailOffice365 { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
