//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositorioAcademico.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RepositorioAcademicoEntities : DbContext
    {
        public RepositorioAcademicoEntities()
            : base("name=RepositorioAcademicoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CentroInvestigacion> CentroInvestigacion { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<TipoTrabajoAcademico> TipoTrabajoAcademico { get; set; }
        public virtual DbSet<TrabajoAcademico> TrabajoAcademico { get; set; }
        public virtual DbSet<TrabajoInvestigacion> TrabajoInvestigacion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
