//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositorioAcademico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrabajoAcademico
    {
        public int id { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public int añoPublicacion { get; set; }
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public string documento { get; set; }
        public int idEstudiante { get; set; }
        public int idCarrera { get; set; }
        public int idTutor { get; set; }
        public int idTipoTrabajoAcademico { get; set; }
        public int idEstado { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual TipoTrabajoAcademico TipoTrabajoAcademico { get; set; }
    }
}
